[package]
org = "wso2"
name = "search_taxes"
version = "1.0.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "hubspot.crm.commerce.taxes"
version = "1.0.0"
repository = "local"